exports.gemini = require('./ai/gemini')
exports.blackbox = require('./ai/blackbox')
exports.text2img = require('./ai/text2img')
exports.gpt4 = require('./ai/gpt4')
exports.eleo = require('./eleo')
exports.hatbaby = require('./hatbaby')
exports.dreamshaper = require('./dreamshaper')
exports.sdlightning = require('./sdlightning')