exports.danbooru = require('./image/danbooru')
exports.gelbooru = require('./image/gelbooru')
exports.rule34 = require('./image/rule34')
exports.nhentai = require('./image/nhentai')
exports.yandere = require(./image/yandere')