exports.facebook = require('./tools/facebook')
exports.instagram = require('./tools/instagram')
exports.tiktok = require('./tools/tiktok')
exports.x = require('./tools/x')
exports.play = require('./tools/play')
exports.subdomain = require('./tools/subdomain')
exports.http = require('./tools/http')